### ISSUE TITLE
Unable to find Cypress AWS Community AMI 

### ISSUE THREAD

**Issue by lrhache** [projectcypress/cypress#1033]
I was unable to find the AWS AMI for Cypress as described in the install instructions:
https://github.com/projectcypress/cypress/wiki/Cypress-4-AMI-Install-Instructions

**Comment by recunius** [comment]
I to am having issues finding the proper AMI. What is the exact name(s) of valid AMIs? I see several that have a name matching "bitnami-edx-cypress*" but how can I verify that these are the proper images for this project?

**Comment by okeefm** [comment]
@lrhache and @recunius: What AWS Region are you in? The Cypress instance is only available in the "US East (N. Virginia)" region. This is because Amazon AMIs are only available in the region they're built in.

**Comment by lrhache** [comment]
@okeefm thanks! I was able to find it by changing the region to US East
