### ISSUE TITLE
Allow setting the --spec cli option through the config

### ISSUE THREAD

**Issue by raineroviir** [projectcypress/cypress#1039]
I would like to have the ability to configure which test files are run through cypress.json or cypress.env.json

As far as I am aware, no such "spec" option exists from the configuration right now.

Workarounds like setting the integrationFolder, isn't ideal in my use case and I would prefer not to set this option in the CLI

Thanks

**Comment by okeefm** [comment]
Hello!

This repository is the source code for Cypress, the Health IT Certification tool (http://healthit.gov/cypress). Based on the issue, I believe you may have meant to post this to the Cypress.io web testing framework repository (https://github.com/cypress-io/cypress). If that's not the case, and you did mean to post to Cypress the Health IT Certification Tool, please feel free to reopen this issue.

Thank you,
Michael O'Keefe
