### ISSUE TITLE
Cypress 4.x support

### ISSUE THREAD

**Issue by jxfish2** [projectcypress/cypress#1042]
Does anyone know when Cypress 4.x might be supported?

We have an application that needs the extra functionality provided in 4.x.

I already verified with our development team, and 3.x does not have everything that we need.

Thanks in advance, and have a great week.

JCF

**Comment by okeefm** [comment]
Hello @jxfish2,

Cypress 4.0.0 was released on July 26, 2018. It includes:
* Support for the 2018 CQL-based Electronic Clinical Quality Measures for 2019 Calendar Year reporting
* Support for the CMS QRDA Cat I Implementation Guide for the 2019 CY Reporting Period
* Support for the HL7 QRDA Cat I R5 and QRDA Cat 3 R2.1 Implementaton Guides

Information on how to download and install Cypress 4.0.0 can be found on our wiki [here](https://github.com/projectcypress/cypress/wiki/Cypress-4-Install-Instructions). 

Please note that we anticipate the release of a Cypress v4.0.1 patch release on October 11, 2018.

If you have any additional questions about Cypress, please feel free to ask us, or to post an issue at https://oncprojectracking.healthit.gov/support/browse/CYPRESS

Thank you,
Michael O'Keefe

**Comment by jxfish2** [comment]
Hi Michael,

Thank you for the response.

Unfortunately, the reason for my post here, was because I had already been to that page, and as I understand it, the new Cypress 4.x is not supported in the format that we need.

My company decided to migrate everything we have to the Azure cloud, instead of to the Amazon cloud.

It appears as if the current image that you offer is in a "VHD" format, but for the Azure cloud, it needs to be in a "VMDK" format.

The "VHD" image will not work in Azure.

Now, Azure does offer a pre-built and configured Ubuntu image with Docker already installed.

If 4.0 has a Docker image that can be downloaded to an Ubuntu server already running Docker, that might work.

Or, if 4.0 has a Docker image that can be downloaded to a CentOS server already running Docker, that would also work.

Note that we use CentOS and RHEL in house, and at customer sites.  We only use Ubuntu, when an application demands Ubuntu.

Any ideas?

Thanks in advance, and have a great day.

JCF

**Comment by okeefm** [comment]
Hello @jxfish2,

Thanks for the response! I'll re-open this ticket, and discuss with the other DevOps people on the Cypress team.

**Comment by rbclark** [comment]
It should be very easy to deploy Cypress using our chef scripts, the instructions for how to do so can be found here: https://github.com/projectcypress/cypress-recipe#chef-solo

If that doesn't work or you have any issues please feel free to let me know.

**Comment by jxfish2** [comment]
Ok, I will try.

Thanks for your time, and have a great afternoon.

JCF

**Comment by okeefm** [comment]
@jxfish2 I'm going to close this ticket as resolved, given the suggestion to use the Chef install script. If you continue to have issues, feel free to comment/re-open the ticket.

Thank you,
Michael
