### ISSUE TITLE
Cannot run Cypress 4.0.0 and CVU together with the same bundle.

### ISSUE THREAD

**Issue by geddawi** [projectcypress/cypress#1049]
Hello,
I tried using the **Chef** option to install Cypress and CVU side by side since its pretty much hassle-free after many trials and errors trying to manually set up everything. This looks like it worked and I could successfully import the bundle (bundle-2018.zip) through the Cypress GUI but this does not work in CVU. Ngninx/CVU gives a familiar error (502) that I've only seen happen when I have a CVU instance installed without a bundle.

I've seen two conflicting views on this page:
1. comment by **okeefm** stating that CVU and Cypress can use the same bundle.
![capture](https://user-images.githubusercontent.com/18403890/46671636-8c78ce00-cbd5-11e8-9143-9cf43046bc14.PNG)

2. Chef installation seems to imply that you need to import the bundle for both or doesn't really clarify the case of installing both together.
![image](https://user-images.githubusercontent.com/18403890/46671743-cf3aa600-cbd5-11e8-8290-796b9a69604f.png)

Is there anything I'm missing? I have a clean Ubuntu machine, with a chef install of the Cypress+CVU option. How do I get the CVU working?

-----------------------------EDIT------------------------------

Clicking on the "Validation Utility" tab in the Cypress 4 GUI at **localhost** redirects me to where the CVU should be running **localhost:8080**

This is the default config file in **sites-enabled** folder in NGINX left untouched: 

```
upstream primary {
  server 127.0.0.1:8000;
}

upstream secondary {
  server 127.0.0.1:8001;
}

server {
  listen 80;
  server_name _;

  root /opt/cypress/public;

  try_files $uri/index.html $uri @app;

  location @app {
    proxy_pass http://primary;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_redirect off;
  }

  location /cvu {
    return 301 http://$host:8080;
  }

  error_page 500 502 503 504 /500.html;

server {
  listen 8080;
  server_name _;

  root /opt/cypress-validation-utility/public;

  try_files $uri/index.html $uri @app;

  location @app {
    proxy_pass http://secondary;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_redirect off;
  }

  error_page 500 502 503 504 /500.html;
  client_max_body_size 4G;
  keepalive_timeout 10;
}
```

**Comment by geddawi** [comment]
Do I run this command on a clean Ubuntu install or on your Cypress 4.0.0 VM?

**Comment by rbclark** [comment]
@geddawi I see there are 2 additional comments that you made which seem to be missing from GitHub (not sure if this is due to the downtime yesterday or not). Are those comments still relevant?

**Comment by geddawi** [comment]
@rbclark No, I had an internal problem which I thought was a problem with your Chef install. So I deleted them so I don't cause you guys any hassle. Thanks for your support, you can close the issue now if you wish! I had a few questions about the actual platform though if you have any spare time, I can send you an email!
