### ISSUE TITLE
Issue with Cypress V4 Chef Install (Cypress + CVU)

### ISSUE THREAD

**Issue by oqureshi2012** [projectcypress/cypress#1055]
Good Morning,

I am running into an issue trying to setup the CVU for my install. I followed all of the chef installation instructions on this page: https://github.com/projectcypress/cypress-recipe#installation-options. 

After installing both Cypress and CVU I am able to get into the GUI but the validation utility is not working. Using this page: https://github.com/projectcypress/cypress/wiki/Cypress-Validation-Utility-Initial-Setup
I was able to run the first command (cd /opt/cypress-validation-utility) but when I tried the second command (/opt/ruby_build/builds/opt/cypress-validation-utility/bin/bundle exec rake bundle:download_and_install version=BUNDLE_VERSION RAILS_ENV=production) it told me that the file/directory does not exist. Please advise on how I can resolve this. Did I miss part of the configuration? I do not see Ruby_Build as a file in that directory.

Thanks

**Comment by jxfish2** [comment]
Note that /opt/ruby_build does not exist.
We are running in the Azure cloud, and Azure is not compatible with your image type.
As such, you told us to build our Ubuntu server with docker already installed.
Then, you told us to use the "chef" instructions to finish the Cypress and CVI installs.
Up to this one last piece, there have been no issues or errors.
However, the /opt/ruby_build directory structure does not exist, using this method.
At what point is the /opt/ruby_build installed?
Is there something we need to do, to install this /opt/ruby_build application?

**Comment by geddawi** [comment]
Same dilemma in trying to get CVU up and running alongside Cypress, already opened an issue ticket about this. After the Chef installation, redirecting to CVU gives a 502 NGINX error and there is no way offered to either get CVU to share the imported bundle from Cypress or get CVU running by importing our own bundle. Please clarify this guys, it's a huge hassle.

**Comment by geddawi** [comment]
I tried manually downloading the `bundle-2018.zip` on the machine and performing a` bundle exec rake bundle:import[.....] `with the respective parameters for that rake call and path to the bundle, but it seems like we can't bundle anything at all in the folder.

**Comment by rbclark** [comment]
It seems the instructions in the Chef README never got updated for Cypress v4. I apologize for that, I've gone ahead and updated them to point to the proper links for Cypress v4. If you have Cypress + CVU installed then any bundles that you install to Cypress via the UI will automatically be seen by the CVU. If you have only installed CVU and need to import a bundle via the command line then you can run `cypress-validation-utility run rake bundle:import[...]`.

Any instructions mentioning `/opt/ruby_build` are for Cypress v3, the ruby version is now packaged within `/opt/cypress/bin`.

**Comment by oqureshi2012** [comment]
Good Morning Robert,

I have uploaded the 2018 bundle via the UI, but I am still getting the 502 error when I click on the Validation Utility. We have already confirmed everything from a infrastructure standpoint so I believe this is still an application issue. Please see the below images for reference and advise on next steps.

![cypress1](https://user-images.githubusercontent.com/44234194/47159824-a47adc80-d2bc-11e8-990f-042703a31dcb.JPG)
![cypress2](https://user-images.githubusercontent.com/44234194/47159888-c6745f00-d2bc-11e8-9035-5afde93e5097.JPG)


Thanks

**Comment by oqureshi2012** [comment]
Another thing I noticed is that we are using Cypress v4.0.1 and the bundle version is 2018.1.0, could there be any compatibility issues?

Thanks

**Comment by oqureshi2012** [comment]
Robert,

I went ahead and ran the update and it did not fix the validation utility. I am still receiving the 502 error message. Please see the image below: it says that the packages cannot be authenticated?


![cypress1](https://user-images.githubusercontent.com/44234194/47181243-7adba880-d2f0-11e8-8aa5-02fc8a213de9.JPG)

**Comment by oqureshi2012** [comment]
Update: we added the --anyauth option to the curl command and were able to get past that error message. Now we get more errors while running the update. See below:

![image](https://user-images.githubusercontent.com/44234194/47183699-b37e8080-d2f6-11e8-933b-a15f70e01232.png)

**Comment by geddawi** [comment]
@jxfish2 I had your same issue and @rbclark 's fix did it for me. Try destroying your current VM/machine OS instance and run the chef install on a clean Ubuntu VM/machine. Then run @rbclark 's shell script command and if/when it hangs hit enter once; it will be waiting for your password for the second part of the command (the execution part after the pipe '|' symbol), enter your password and it should work.

> It turns out there was an issue with our build process for CVU v4. We have rebuilt the CVU v4 package, could you try installing it by running
> 
> ```
> curl https://raw.githubusercontent.com/projectcypress/cypress/v4.0.1.1/contrib/upgrade_cypress_40.sh | sudo bash
> ```
> and report back whether this works?

**Comment by rbclark** [comment]
@jxfish2 Your problem sounds related to something specific to your environment, we have been able to verify it is working on our end and it seems a few people in this thread have been able to successfully run it as well. The script itself is just pulling from apt. Can you verify that all your OS packages are fully up to date and that there is no MITM proxy or something else messing with your traffic?

@oqureshi2012 The updates that we pushed out should actually not require you to run the upgrade script if you do a clean build with Chef. A clean build with Chef should include all of the new changes we have made.

**Comment by okeefm** [comment]
@oqureshi2012 I'm going to close this issue as resolved. If you're continuing to experience issues with your install, please feel free to comment/re-open the issue.

Thank you,
Michael O'Keefe
