### ISSUE TITLE
Filesystem ownership

### ISSUE THREAD

**Issue by jxfish2** [projectcypress/cypress#1056]
I am very unhappy with the filesystem ownership and group.
It is unrealistic, and cumbersome, to use User and Group names more than 8 to 10 characters in length.
Can I change the filesystem owner and group to something shorter?
I can not realistically use the UserID and Group name:  "cypress-validation-utility".
Will it break anything, if I shorten the UserID and GroupID to "cypress", or "cvi"?  (Or something equivalent)

**Comment by jxfish2** [comment]
It's an aesthetics thing.

If you look at the following screenshots, which one is more appealing?

![image](https://user-images.githubusercontent.com/39163092/47163547-35a18180-d2c4-11e8-823e-833b42a02ba5.png)

![image](https://user-images.githubusercontent.com/39163092/47163597-4d790580-d2c4-11e8-894b-1de4774bff0d.png)

Note that it's much easier to read, when you can eliminate the word wrap.  

You can only do this by limiting the length of "data" in each field.

By keeping userID's, groupID's and directory names to a shorter length, it makes everything much easier to read.

If for some reason, you're trying to build a database table, your field lengths need to be at least as long as your longest entries.

It's just not an efficient use of space.

Please do not misunderstand me.

I really appreciate all of the development work that you and your team are doing here.

I just feel that when developers create code and applications, they sometimes don't look at the big picture, and they can not see what every end user's needs might be.

When laying out filesystems.  When creating UserID, GroupID and directory structures, all I'm asking is that you look at aesthetics, when displaying output to the screen, and if you needed to build a database table, how efficiently could you populate the table, with the existing conventions?

Thanks for your time and effort, and have a wonderful week.

**Comment by rbclark** [comment]
We can keep this in mind for future releases, but changing this now has a chance of breaking existing deployments which is unacceptable. Also, I'd say making it easier for a user to easily identify what the purpose of a user account is also an important consider. If we were to change the username to CVU and some random administrator logged in, they would easily be able to do a search for `cypress-validation-utility`, on the other hand doing a google search for `cvu` or `cvu cypress` even does not render the most helpful results.
