### ISSUE TITLE
Cypress v4 VM Install Issue

### ISSUE THREAD

**Issue by oqureshi2012** [projectcypress/cypress#1059]
Good Afternoon,

We are trying to deploy Cypress V4 using the ova file you provided here:
https://github.com/projectcypress/cypress/wiki/Cypress-4-VM-Install-Instructions
But we are running into an issue when standing up the image. It says that the OS is not found. Please advise. See the below image.
![cypress1](https://user-images.githubusercontent.com/44234194/47525158-8daf2980-d86a-11e8-81c9-4aa9b606d107.PNG)

**Comment by rbclark** [comment]
With our latest build of Cypress it seems that an update to the build environment has caused some incompatibilities with older versions of VMware products. What version of ESXi are you currently running?

**Comment by oqureshi2012** [comment]
We are currently using version 5.5

**Comment by oqureshi2012** [comment]
Good Evening,
Did we have any potential solutions to this problem?
Thanks

**Comment by rbclark** [comment]
We are still investigating building with support for older hypervisors. In the meantime, I suggest downloading the Cypress 4.0.0 VM at https://s3.amazonaws.com/cypress_public/Cypress.v4.0.0_Public_VM.ova and run the upgrade script. Since that VM was built with a slightly older version of VMware it should work fine.

**Comment by oqureshi2012** [comment]
Robert,

Thank you we will go ahead and try that image. However, what upgrade script are you referring to? That link takes me directly to the download.

**Comment by rbclark** [comment]
My mistake, the upgrade script can be found here: https://github.com/projectcypress/cypress/wiki/Cypress-4.x-Upgrade-Instructions

**Comment by oqureshi2012** [comment]
Good Morning Robert,

Before I run the upgrade script I wanted to make sure that the application is working as designed. We uploaded the older version of Cypress v4 that you provided and it looks like that worked. However, after I import a bundle and I click on the "Validation Utility" button it says that the page can not be found. Did we miss something in the config? Do I need to run the upgrade command in order to the validation utility to work?

![image](https://user-images.githubusercontent.com/44234194/47787148-5adeb880-dce4-11e8-81ad-e55f9a682c3b.png)

Thanks

**Comment by rbclark** [comment]
@oqureshi2012 This is actually an issue in 4.0.0 that is fixed with 4.0.1, so going ahead and running the upgrade script should correct this for you.

**Comment by okeefm** [comment]
@oqureshi2012 I'm going to close this ticket as resolved. If the upgrade did not solve this issue for you, please feel free to comment/re-open this ticket.

Thank you,
Michael O'Keefe
