### ISSUE TITLE
Cypress Issue with Bundle

### ISSUE THREAD

**Issue by oqureshi2012** [projectcypress/cypress#1062]
We are not getting 2018 data generated in our Cypress and have bundle 2018.1.0. Looks like we have bundle mismatch with the proctor, but cannot find link to download bundle 2018.0.1. Can you provide by chance?

**Comment by okeefm** [comment]
Hello @oqureshi2012,

The Cypress 2018.0.1 bundle is available at https://cypressdemo.healthit.gov/measure_bundles/bundle-2018.0.1.zip . As a note, you will need a valid UMLS Terminology Services account to download this bundle, as with all bundles.

Thank you,
Michael O'Keefe

**Comment by oqureshi2012** [comment]
Thank you for the quick response!
