### ISSUE TITLE
BSONObj exceeded maximum nested object depth error importing bundle-2018.zip

### ISSUE THREAD

**Issue by iamtheschmitzer** [projectcypress/cypress#1112]
When saving measure from CMS156v7a and CMS156v7b

> AssertionException handling request, closing client connection: 22 Client Error: bad object in message: BSONObj exceeded maximum nested object depth: 200

Mongo appears to NOT be configurable in this depth https://docs.mongodb.com/manual/reference/limits/#bson-documents

How did you get around the issue?

Thanks In Advance

**Comment by rbclark** [comment]
Could you clarify how you installed Cypress? Our automated installers set mongo to have a larger nested object depth: https://github.com/projectcypress/cypress-recipe/blob/master/files/default/mongod.conf#L26-L28

Can you verify that this setting is present in /etc/mongod.conf?
