### ISSUE TITLE
CMS249 C1 DENEX Error for patient template 3 N GP Adult

### ISSUE THREAD

**Issue by iamtheschmitzer** [projectcypress/cypress#1241]
For CMS249v1, I get an error no matter what file I provide for the patient template `3 N GP Adult`:
> Calculated value (0) for DENEX (0FB2B684-8D8D-44C6-9945-0B16543FF95E) does not match expected value (1)

I have even tried substituting the source XML file for that patient in my own zip file that I upload and that fails as well.  

I believe this patient should qualify for DENEX because of `Age Dependent Combination Risk Factors` of 
* Current Tobacco User
* First BMI in Measurement Period Less Than or Equal to 20 kg m2
* Patient Characteristic Race: White

Can you please help?  Should the race white be presented as an `<entry>`?

**Comment by dczulada** [comment]
Jeff-

Could you post this issue to the Cypress Issue Tracker.
https://oncprojectracking.healthit.gov/support/projects/CYPRESS

-Dave

**Comment by iamtheschmitzer** [comment]
Thanks was just wondering if there was a place there for it!

**Comment by iamtheschmitzer** [comment]
Done https://oncprojectracking.healthit.gov/support/browse/CYPRESS-1833

**Comment by iamtheschmitzer** [comment]
Confirmed this is fixed by updating cypress version, closing
