### ISSUE TITLE
Undefined method 'normalize_date_times'

### ISSUE THREAD

**Issue by skaranfilovski** [projectcypress/cypress#1734]
Hi there,

While validating our QRDA I files with CMS22v10 Measure Test (cypress 7.0.1) we are getting the following error:

![image](https://user-images.githubusercontent.com/85104290/181510228-87392d78-e840-48a9-a9be-dd4372c7891f.png)

We compared it with our other QRDA I files but we are unable to find the cause for the problem. It would be very helpful if you can point us in the right direction :).

Here is the file that is throwing that error:

[GP_Adult_TWO_N_Long_Care_ONE_58.txt](https://github.com/projectcypress/cypress/files/9209755/GP_Adult_TWO_N_Long_Care_ONE_58.txt)

Thanks!

**Comment by dczulada** [comment]
Sorry for the delay

I believe the issue in the attached file is with the following time range.  The high value should either have a valid time value, or use the nullFlavor.

```
<effectiveTime>
	<low value="20181104060000+0200" inclusive="false"/>
	<high value="" inclusive="false"/>
</effectiveTime>
```

-Dave Czulada

**Comment by skaranfilovski** [comment]
Hello Dave,

That indeed was the issue, thanks for the clarification :),

Stefan
