### ISSUE TITLE
Browser not opening Cypress interface.

### ISSUE THREAD

**Issue by ajbehzadi** [projectcypress/cypress#1898]
Installed Cypress 7.3.1_Public_VM using  https://s3.amazonaws.com/cypress_public/Cypress.cypress_7.3.1_Public_VM.ova.
Configured network and ping is responding.  I tried different browsers but still I get the error: 
Did the same thing last year and it worked just fine.  Is there a setting that I need to change like port #, or some other settings?
Has anything changed in this release?

**Comment by dczulada** [comment]
Could you describe the system you are installing Cypress on?  Are you on a Mac, PC, etc.?  Are you running the VM in VirtualBox or VMWare player?

**Comment by ajbehzadi** [comment]
Thank you for your response.
 
I downloaded Cypress.cypress_7.3.1_Public_VM.ova and created a V-Server.  That package includes UBUNTU 22.04.4 LTS and Cypress v7.3.1.
 
We have done this with the different .OVAs for Cypress and have had no issues.
 
We get the error when we use a browser to access the IP address of the server.  This is the Error:
 
502 Bad Gateway
  _____  

nginx/1.18.0 (Ubuntu)
 
I did some research, and the consensus is to increase buffer size:
proxy_connect_timeout 600; 
proxy_send_timeout 600; 
proxy_read_timeout 600; 
send_timeout 600;
 
 
Still getting that error.
 
 
 
Arash J Behzadi MCSA
IT Specialist

 <http://www.primeclinical.com/> Prime Clinical Systems, Inc.
3675 E Huntington Dr  Ste A
Pasadena CA 91107  
626-449-1705  Ext. 283
***@***.***

**Comment by dczulada** [comment]
Arash

We'll try to dig in to see what's going on here.

Would you be able to try installing an older Cypress OVA (e.g., 7.2.2 linked below)?
https://s3.amazonaws.com/cypress_public/Cypress.cypress_7.2.2_Public_VM.ova

If installing the older version works, you can run the upgrade script to bring it up to 7.3.1.
https://github.com/projectcypress/cypress/wiki/Cypress-7.x-Upgrade-Instructions

-Dave Czulada

**Comment by ajbehzadi** [comment]
Thank you for your reply.
 
I will go ahead and do this and let you know.
 
Arash J Behzadi MCSA
IT Specialist

 <http://www.primeclinical.com/> Prime Clinical Systems, Inc.
3675 E Huntington Dr  Ste A
Pasadena CA 91107  
626-449-1705  Ext. 283
***@***.***

**Comment by ajbehzadi** [comment]
Getting the same error as before.
 
504 Gateway Time-out
  _____  

nginx/1.18.0 (Ubuntu)
 
Is there a specific error log that I can examine that would shed a light on this?
 
 
Arash J Behzadi MCSA
IT Specialist

 <http://www.primeclinical.com/> Prime Clinical Systems, Inc.
3675 E Huntington Dr  Ste A
Pasadena CA 91107  
626-449-1705  Ext. 283
***@***.***

**Comment by ajbehzadi** [comment]
Good morning Dave,
 
Any suggestions?
 
The testing period is almost over.  I would appreciate any help at this point.
 
Arash J Behzadi MCSA
IT Specialist

 <http://www.primeclinical.com/> Prime Clinical Systems, Inc.
3675 E Huntington Dr  Ste A
Pasadena CA 91107  
626-449-1705  Ext. 283
***@***.***
 
From: Arash J Behzadi 
Sent: Friday, October 18, 2024 11:53 AM
To: 'projectcypress/cypress' ***@***.***>; 'projectcypress/cypress' ***@***.***>
Cc: 'Author' ***@***.***>
Subject: RE: [projectcypress/cypress] Browser not opening Cypress interface. (Issue #1898)
 
Getting the same error as before.
 
504 Gateway Time-out
  _____  

nginx/1.18.0 (Ubuntu)
 
Is there a specific error log that I can examine that would shed a light on this?
 
 
Arash J Behzadi MCSA
IT Specialist

Prime Clinical Systems, Inc. <http://www.primeclinical.com/> 
3675 E Huntington Dr  Ste A
Pasadena CA 91107  
626-449-1705  Ext. 283
***@***.*** ***@***.***>

**Comment by dczulada** [comment]
Arash-

It's hard to determine what could be going on here.  In the interest of time, you might want to utilize the Cypress demo server.

https://cypressdemo.healthit.gov/users/sign_in

-Dave Czulada

**Comment by schallot** [comment]
For what it's worth, I'm seeing the same error.  

504 Gateway Time-out
nginx/1.18.0 (Ubuntu)

It happens when I run Cypress.cypress_7.3.1_Public_VM.ova in VirtualBox Version 7.0.2 r154219 (Qt5.15.2), and I saw the same error when I tried the 7.3.1 Cypress Community AMI image in AWS

**Comment by ajbehzadi** [comment]
Yeah, it has to do with NGINX.  I tried configuring it based on what I found on the net.  php-fmp is not functioning correctly.  Proxy settings.  I went down the rabbit whole on this.
Our developers stated they will do the test and certification on the Demo Server at the gov site.

**Comment by schallot** [comment]
For anyone who's curious, I worked my way through the various v7 ova files, and it looks like this problem first appears with 7.1 images, from 7.1.0 up through the current 7.3.1.  The most recent working version I've found is 
https://s3.amazonaws.com/cypress_public/Cypress.cypress_7.0.4_Public_VM.ova
I was able to upgrade from 7.0.4 to 7.3.1 using https://github.com/projectcypress/cypress/wiki/Cypress-7.x-Upgrade-Instructions

FWIW, I suspect it's not just an NGINX issue, because when I try bypassing nginx by directly hitting port 8000 I get no response at all starting with 7.1.
I also noticed that when I upgraded from 7.0.4, MongoDB failed to upgrade due to invalid signatures.  Perhaps the reason that the older versions are still working is because of something related to MongoDB, and the failed MongoDB update is allowing the Cypress upgrade to succeed?

**Comment by ajbehzadi** [comment]
schallot,

Thank you for these directions.  It worked for me.
My mistake was trying upgrade from 6.0.2  and 7.2.XX to 7.3.1 and it didn't work.  Like you said the trick is to install 7.0.4 (Thank you for the link) and then update to 7.3.1.



dczulada,

You were on the right track except for the version to install.  I appreciate the time you spent trying to help me.  Hopefully , if anyone else is stuck, they can use this fix.
