### ISSUE TITLE
offtopic: CCRs and lab results

### ISSUE THREAD

**Issue by mrose17** [projectcypress/cypress#306]
sorry for the noise (but i can't find email addresses for either of you!)

would it be possible to get a pointer to how one encodes lab results via CCR? neither LabCorp nor Quest Diagnostics have a download "CCR" (or "CCD") button, but only a "PDF" button.

fine, i can run http://tabula.technology/ as well as anyone else and clean up the output. and i can write a transformation program ... if i know what the format/dictionary is... would you be able to help?

many thanks!

/mtr

**Comment by ssayer** [comment]
I'm not sure if You meant to post this here, but Cypress doesn't have anything to do with CCR.

**Comment by mrose17** [comment]
thank you very much... in truth, i realize that while the repo might not be current, as a contributor, you know a lot more than i do.

best,

/mtr
