### ISSUE TITLE
Counts getting miss match due to consolidated Calculation of Measures from Test Deck of Cypress 3.0 Alpha

### ISSUE THREAD

**Issue by sudhir-nair** [projectcypress/cypress#400]
We have started testing the Pre-Release Cypress3.0 Alpha. We are facing an issue because the consolidate list of patients are measure wise, whereas our process will run once and calculate status for all patient or visit at once. While generating QRDA III, we are facing issue because few of the patient\visit are getting calculated for other measures due to which Cypress provided count and our count are not matching. Our count is always greater than what cypress has provided due to patients getting qualified across multiple Measures. Please let us know, is this logic the final in Cypress 3.0 or is there supposed to be changed.

**Comment by dczulada** [comment]
Is the the currently flow of your process?

1) Create Product (with multiple measures)
2) Download all patients for all measures
3) Upload all patient for all measures
4) Generate QRDA III files for all measrues (using all patients in your system)
5) Upload generated QRDA III files into Cypress

-Dave

**Comment by sudhir-nair** [comment]
Yes that's exactly the current flow of our process. This flow fails with the current version of Cypress3.0 Alpha.

**Comment by dczulada** [comment]
That is correct.  That workflow does fail with Cypress 3.  However, this is done by design.

Cypress has been developed for single measure testing.  The patients provided for each measure test should only be used for that single measure.
