### ISSUE TITLE
Test Patients not getting generated in New version 6alpha

### ISSUE THREAD

**Issue by sudhir-nair** [projectcypress/cypress#486]
Test Patients not getting generated in New version 6alpha. Check production.log, something is gone in Infinite loop. I tried for CMS100.

**Comment by dczulada** [comment]
Are you using the Virtual Machine distribution? or the demo server?

If you are using your own Virtual Machine, can you attach the log file.

**Comment by sudhir-nair** [comment]
Am using the Virtual Machine distribution. Downloaded the latest one. After re-installation again from scratch it has started generating, I cannot find error now. Will update if error is reproduced

**Comment by dczulada** [comment]
Do you remember what type of test was hanging? Was it the CMS100 "Measure Test" or the CMS100 "CQM Filtering Test"?
Also, what Bundle do you have installed? bundle-2015-alpha-20160224.zip or bundle-2015-alpha-20160512.zip?

**Comment by sudhir-nair** [comment]
It was CMS100 Measure test. Am using 2015-alpha-20160512 bundle
