### ISSUE TITLE
Cypress getting crashed while uploading QRDA III

### ISSUE THREAD

**Issue by sudhir-nair** [projectcypress/cypress#493]
It is giving following error.
 Server Error
Something went wrong with this request. This is likely a problem with Cypress rather than a mistake on your part. Please find attached xml file just rename it to .xml.

File is a QRDA III xml for CMS111

[QRDA3 (1).txt](https://github.com/projectcypress/cypress/files/297724/QRDA3.1.txt)

**Comment by ssayer** [comment]
Sudhir,

Can you confirm you're on the latest release (Alpha 6)?

-Sam

**Comment by sudhir-nair** [comment]
Yes am using Alpha 6

**Comment by sudhir-nair** [comment]
Am unable to retry upload of QRDA III file now.Seems like i need to create a new product and reprocess complete data.

**Comment by ssayer** [comment]
Sudhir,

If you’re going to lose a non-trivial amount of work, we can try to find a workaround once we’re done testing your file.

-Sam

**Comment by sudhir-nair** [comment]
It's fine...I can reprocess. Just let me know what went wrong.

**Comment by dczulada** [comment]
Thanks for pointing this out.  There is a bug in Cypress that is preventing displaying the error message related to the file you uploaded.

The error in your file is related to the OBSERV id.  The file you attached is still using the id "b9352e6d-c82d-424a-a1d3-05a1f3fbaed3" from the measures released in 2014.  This id needs to be updated to "C71EF921-C721-477D-AB8A-14FB9A19C50D."  I've uploaded a file making that change which should now work.

[QRDA3.1.txt](https://github.com/projectcypress/cypress/files/297843/QRDA3.1.txt)

**Comment by ssayer** [comment]
Sudhir,

This should be fixed in the latest beta1 release. If it is not, please reopen
