### ISSUE TITLE
For CMS188 Route Code missing for Patient Data

### ISSUE THREAD

**Issue by sudhir-nair** [projectcypress/cypress#516]
For CMS188, as per the measure spec it says Medication, Administered: IV, IM, PO Antimicrobial Medications (route: Substance or Medication Administration Route IV, oral or IM)" satisfies any.
Whereas cypress provided data doesn't have any route code. Please find attachment. Am using the latest cypress 3.0.0alpha6.
Just rename txt to xml.
[1_2_N CAP.txt](https://github.com/projectcypress/cypress/files/325057/1_2_N.CAP.txt)

**Comment by dczulada** [comment]
Yes.  There are some patients that have the route specified, and others that do not have the route specified.  The patients that do not have the route specified do not meet the population criteria.

**Comment by sudhir-nair** [comment]
But the sample which I have attached as per the test scenario, patient needs to qualified for both denominator and denominator exclusion.

**Comment by souravkhemka** [comment]
![2_n_cap](https://cloud.githubusercontent.com/assets/20084778/16258783/f7f77f6c-387c-11e6-85d9-a93b49295fb8.png)
But the above patient is qualifying denominator and hence exclusion as per Cypress status. Please find the screenshot of the patient status
