### ISSUE TITLE
For CMS171 none of the patients fall under DENEXCEP as per cypress but it expects the same in Cat 3

### ISSUE THREAD

**Issue by souravkhemka** [projectcypress/cypress#523]
In Cms 171, none of the patients qualifies for DENEXCEP in any part; whereas cypress excepts the DENEXCEP entry for 0 count measures in cat 3 file. I have checked in the measure xml of cms,  exception is mentioned as NONE. Please find the attached screenshot of the Cat 3 error in cypress.
Am using the latest cypress 3.0.0alpha6.
![cms171cat3](https://cloud.githubusercontent.com/assets/20084778/16259068/70dce682-387e-11e6-9d7c-b01254625161.png)

**Comment by dczulada** [comment]
Thanks.  This is a known issue with the May test bundle.  This will be fixed in the next Cypress/bundle release.  The following JIRA ticket discusses this issue, and lists all the measures that you may see this type of error.

https://jira.oncprojectracking.org/browse/CYPRESS-668

**Comment by souravkhemka** [comment]
I cannot see CMS171 and CMS 66 in the list which you have mentioned. Can you please add this in the list
