### ISSUE TITLE
Reopening issue 516

### ISSUE THREAD

**Issue by sudhir-nair** [projectcypress/cypress#524]
Please find attached screenshot, wherein it says patient to be qualified for Denominator & Denominator Exclusion for CMS 188.
[1_2_N CAP.txt](https://github.com/projectcypress/cypress/files/327334/1_2_N.CAP.txt)

![capture](https://cloud.githubusercontent.com/assets/18002170/16260490/4a33fd2a-3885-11e6-9cb6-9e88acff5105.JPG)

**Comment by dczulada** [comment]
Thanks for following through with this.  The human readable version of the measure i was looking at did not show the route as a requirement for the Medication, Administered element in the Denominator.

However, this route is included in the released human readable provided in the eCQM specifciations

![screen shot 2016-06-22 at 1 50 41 pm](https://cloud.githubusercontent.com/assets/8173551/16277308/60a728e8-3880-11e6-8f9d-0c5fcea5c49b.png)

This looks like it could be a bug in the measure specification, can you please post this to the CYPRESS JIRA (https://jira.oncprojectracking.org/browse/CYPRESS) for us to check with the measure developers.

Thanks

**Comment by dczulada** [comment]
I opened a ticket on the CQM JIRA for this issue 

https://jira.oncprojectracking.org/browse/CQM-2057
