### ISSUE TITLE
For CMS73v4, IPP count is expected as 2.0 instead of 1.0 error in Cat 1 file

### ISSUE THREAD

**Issue by souravkhemka** [projectcypress/cypress#535]
A patient "5 N VTE" gets denominator inclusion failed for 2 visits as shown below
![cms73patientstatus](https://cloud.githubusercontent.com/assets/20084778/16289011/2ea499a4-390f-11e6-975b-e7ceff033cbc.png)
The CAT 1 generated has details for both the visits and the error should not persist.
Please find the screenshot of the error for cat1 and the output file attached of the patient
![cms73cat1failed](https://cloud.githubusercontent.com/assets/20084778/16289039/6e1a6fc8-390f-11e6-8cc3-0c751035afb5.png)
[5_N VTE.txt](https://github.com/projectcypress/cypress/files/329027/5_N.VTE.txt)

**Comment by souravkhemka** [comment]
Any update on this ticket?

**Comment by dczulada** [comment]
Hi

This is an episode of care measure.  Each episode that meets the population criteria is counted.

The attached patient has two diagnoses that start within two encounters

 Diagnosis of Venous Thromboembolism during an encounter on April 1st, and a diagnosis of Obstetrics VTE during an encounter on May 17th.

-Dave Czulada
