### ISSUE TITLE
ID root tag is validated in the cypress but its not necessary

### ISSUE THREAD

**Issue by souravkhemka** [projectcypress/cypress#538]
It have been observed that ID root and extension are checked in the cypress for uniqueness in each tag for the Cat 1 files.
But the value of ID is not used in any measure calculation or its mentioned anywhere; so ideally this should not be validated in cypress

**Comment by souravkhemka** [comment]
Any update on this ticket?

**Comment by dczulada** [comment]
Hi, 

How are you observing the ID being validated?  Are you seeing error messages being returned when ID are not unique?

-Dave Czulada

**Comment by souravkhemka** [comment]
Yes, we have seen in the Cat 1 file. We were getting the following error
**IPP count is expected as 2.0 instead of 1.0 error in Cat 1 file**
We then debugged and tried changing the ID with unique values in the file and uploaded. The file passed in this scenario

**Comment by dczulada** [comment]
Can you attach the files in question?

The original Cypress QRDA file, and the Cat I you generated?

**Comment by ssayer** [comment]
@souravkhemka Please attach the Cypress test patients and your test patients so we can investigate this issue.

**Comment by souravkhemka** [comment]
Hi
Please find below the file of the Cypress patient
[3_5_N VTE.txt](https://github.com/projectcypress/cypress/files/349297/3_5_N.VTE.txt)

PFB the patients file we generated
[5_N VTE.txt](https://github.com/projectcypress/cypress/files/349303/5_N.VTE.txt)

This is for CMS73 measure and it gives an error below
![cms73error](https://cloud.githubusercontent.com/assets/20084778/16611167/483fb1d2-437d-11e6-84e9-067e5a0cf2de.png)

We have changed the root value as uniques for each iagnosis Act entity as can be seen in the below file
[5_N VTE_uniqueroot.txt](https://github.com/projectcypress/cypress/files/349309/5_N.VTE_uniqueroot.txt)
After changing and uploading, the error is resolved in Cypress

**Comment by souravkhemka** [comment]
Sure. Thanks for your updates
