### ISSUE TITLE
Cypress 3.0.0beta1 Corrupt VM File

### ISSUE THREAD

**Issue by sudhir-nair** [projectcypress/cypress#548]
The new link provided is giving corrupted VM files.
https://s3.amazonaws.com/cypress_public/Cypress_v3.0.0beta1_Public_VM.ovf.tar.gz

Also installation only talks about 2015 Bundles, Can we install Both Bundles at the same time??

**Comment by ssayer** [comment]
Sudhir,

I have updated the install instructions with information about how to install both the 2015 and 2016 measures.

I was able to download the VM using the link you posted. The system loaded (using VirtualBox) and I was able to login as normal.

Can you please let us know what VM software you're using (VirtualBox, VMware Player, etc.) and what error message you're getting? Also, have you tried re-downloading the VM?

**Comment by sudhir-nair** [comment]
![capture](https://cloud.githubusercontent.com/assets/18002170/16453379/485f6b24-3e2a-11e6-8d74-4de4956006cf.JPG)

It's not extracting the vm

**Comment by ssayer** [comment]
Sudhir, we're investigating why WinRAR won't open the zip file. In the meantime, We've had consistent success opening the ZIP file with 7zip on Windows (http://www.7-zip.org).

**Comment by gitouttatown** [comment]
Currently the download link for the VM image file (https://s3.amazonaws.com/cypress_public/Cypress_v3.0.0beta1_Public_VM.ovf.tar.gz ) doesn't work. It shows an XML file with "access denied" as shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>938836815E04AA62</RequestId>
<HostId>
fp5ab2M2/AqPXG3P+nPkBT+zGdysN8BytMuu1GY01aT71A7YwV6zOrH7NN64Den2W9SFbrhFZyk=
</HostId>
</Error>

**Comment by ssayer** [comment]
We're currently in the process of uploading a new VM to address the issue with WinRAR. I'll post again when the new version is uploaded.

**Comment by rbclark** [comment]
New download links are now available.

**Comment by ssayer** [comment]
We have tested the new download with WinZIP, WinRAR, 7Zip and Unarchiver (Mac). Please let us know if you are able to successfully download and unzip the VM.

**Comment by sudhir-nair** [comment]
Am able to download but could not install Bundles into it. Below screenshot is the Trace and command.
![capture](https://cloud.githubusercontent.com/assets/18002170/16482453/72a26b90-3ecd-11e6-9c42-6ac65ed30a2e.JPG)

**Comment by sudhir-nair** [comment]
![capture](https://cloud.githubusercontent.com/assets/18002170/16482535/cad2db2e-3ecd-11e6-9ed1-9eeaea5f0e26.JPG)

**Comment by rbclark** [comment]
A new version of the VM has been added, there are two options to fix this issue:

1. Download the new image.
2. Run `ip link show` and note the interface name (for example ens32) edit `/etc/network/interfaces` and update the two instances of the primary network interface to the new interface name.

**Comment by sudhir-nair** [comment]
I downloaded new VM and was able to install bundles but am not able to create Vendors in it.
It is showing access denied.
![capture](https://cloud.githubusercontent.com/assets/18002170/16517848/43d85fd8-3f9d-11e6-9599-799a397f9ddf.JPG)

**Comment by srmouse82** [comment]
I'm having the exact same issue as sudhir, just downloaded the VM today, running it in virtual box

![cyp](https://cloud.githubusercontent.com/assets/20246399/16528721/6c994a88-3f73-11e6-935b-9b99fab1263c.jpg)

**Comment by srmouse82** [comment]
In addition to that, I'm getting the error below when trying to view the master patient list.

![cyp2](https://cloud.githubusercontent.com/assets/20246399/16533613/e96b949c-3f8e-11e6-9448-df2b390ffab2.jpg)

**Comment by ssayer** [comment]
@sudhir-nair @srmouse82 can you please attach your logs so that we can see what error is occurring?

**Comment by sudhir-nair** [comment]
Can you please provide path of the log file in the Linux system , so that I can upload it

**Comment by sudhir-nair** [comment]
![capture](https://cloud.githubusercontent.com/assets/18002170/16585664/adcac31e-42df-11e6-95a5-a068a746f775.JPG)

**Comment by sudhir-nair** [comment]
[production.txt](https://github.com/projectcypress/cypress/files/347775/production.txt)

**Comment by ssayer** [comment]
@sudhir-nair what happens if you create a new account? are you able to log in and perform any functions?

**Comment by sudhir-nair** [comment]
I am able to login. I can view Master Patient List, I can view Dashboard. But cannot Add new vendor

**Comment by ssayer** [comment]
is it a 500 "server error" or 403 "forbidden/unauthorized access" error?

**Comment by sudhir-nair** [comment]
You are not authorized to access this page.

**Comment by sudhir-nair** [comment]
no error codes 500 or 403

**Comment by ssayer** [comment]
@srmouse82 I'm going to close this issue because we've fixed the 401 error. Please create a new ticket and attach your logs and we can take a look at the 500 server error, which likely has a different cause than the 401 errors

**Comment by srmouse82** [comment]
@ssayer 
 
Will do, thanks! BTW, the command line trick worked to fix the Vendor issue, but now I also get a 500 error when trying to add a product. I'll add the log file to the new ticket.
