### ISSUE TITLE
Beta 1 500 errors

### ISSUE THREAD

**Issue by MatthewDynamic** [projectcypress/cypress#551]
I am having quite a bit of trouble getting beta 1 working. I have spent a number of hours on this but have been unable to successfully create a vendor and a product.

I am using the VM method. Though I have not tried re-downloading the VM in case you may have updated it since beta1 initial release.

Additionally I have tried installing from source but it appears there are some problems with the instructions for this method. I will save this for another post if I feel adventurous. 

Here are the steps I followed in attempt to install the VM. I have tried a few times with similar results.

Import virtual machine
edit /etc/network/interfaces
Putty in

sudo su - cypress
cd /opt/cypress
/opt/ruby_build/builds/opt/cypress/bin/bundle exec rake bundle:download_and_install version=2015-beta-20160623 RAILS_ENV=production

Register user
Sign in
Log out

Set user as admin
/opt/ruby_build/builds/opt/cypress/bin/bundle exec rake cypress:add_admin['existinguser@myaddress.com'] RAILS_ENV=production

Sign in
Admin -> Bundles -> Set Default the only bundle (2015 Bundle for the 2016 Reporting Period)

Dashboard
Add Vendor (name Api Tests, id ApiTests), success
Click API Tests vendor
Add Product (name TestProduct, c1-c4, uncheck randomize and duplicate, All eCQMs)
After about a minute 502 Bad Gateway nginx/1.10.0 (Ubuntu)

At this point I can see the VM is writing to hard disk so I am letting it sit until activity stops
Site not responding
Delete cookies and attempt to sign in again, browser reports page isn't working
Landing page works but any attempts to sign in fail

sudo shutdown -r now

Wait for activity to calm down
Sign in successfully
Click on my new vendor
Click on testproduct

"90 of 93 measures ready"
Wait two hours
Refresh page results in 500 error
Entire site no longer seems responsive - results in Server Error trying to access login page
Sometimes it works
"90 of 93 measures ready"
Sometimes 500 error

**Comment by okeefm** [comment]
Hello Matthew,

Could you provide the log file, present at `/opt/ruby_build/builds/opt/cypress/log/production.log`? This will help us in diagnosing the issue. If you don't wish to provide the file publicly, please feel free to email it to me at mokeefe <at> mitre <dot> org

Thank you,
Michael O'Keefe

**Comment by MatthewDynamic** [comment]
Email sent. Thank you for looking into this.

**Comment by okeefm** [comment]
Hey Matthew,

We believe this is due to an issue with the latest version of MongoDB. To confirm, can you send your MongoDB logs, which should be present at `/var/log/mongodb/mongodb.log`?

**Comment by MatthewDynamic** [comment]
Email sent.

**Comment by ssayer** [comment]
Matt,

It looks like the MongoDB version 3.2 in beta1 is causing segmentation faults when running measure calculation. We've locked the version of MongoDB we're using to 3.0 in beta2, so this issue should be fixed on Thursday. If you run into this issue in beta2 (you can search the MongoDB logs for "Segmentation fault", please reopen this issue
