### ISSUE TITLE
Cypress Validator Site Crashing 

### ISSUE THREAD

**Issue by sudhir-nair** [projectcypress/cypress#556]
This is regarding https://validator.projectcypress.org/ . I don't know whether this is the right place to post it or not.

[updated patient.txt](https://github.com/projectcypress/cypress/files/343268/updated.patient.txt)
[valuetag_CD.txt](https://github.com/projectcypress/cypress/files/343269/valuetag_CD.txt)
![capture2](https://cloud.githubusercontent.com/assets/18002170/16519135/8dcd390e-3fa4-11e6-8d4c-f8aedd42ff7f.JPG)
![capture](https://cloud.githubusercontent.com/assets/18002170/16519134/8dccc30c-3fa4-11e6-9ca3-59005b3406ee.JPG)

**Comment by ssayer** [comment]
@sudhir-nair can you tell us which settings you selected when submitting the files?

**Comment by sudhir-nair** [comment]
![capture](https://cloud.githubusercontent.com/assets/18002170/16585510/e1136114-42de-11e6-86f1-89add1fe194d.JPG)

**Comment by dehall** [comment]
The issue should be resolved now - it looks like the bundle had not loaded properly. I've tested both of your files and both produce results as expected.
