### ISSUE TITLE
Issue with validator cypress

### ISSUE THREAD

**Issue by souravkhemka** [projectcypress/cypress#560]
Hi,
I have been using the below cypress validator for checking QRDA I and III files.
https://validator.projectcypress.org
The website has  recently been upgraded and now we are facing some issues in the QRDA I files which were working before.
![validatorerror](https://cloud.githubusercontent.com/assets/20084778/16583100/ea456d9e-42d0-11e6-87e8-f076b19336a6.png)
Please find the attached file
[Priority code with negation.txt](https://github.com/projectcypress/cypress/files/347631/Priority.code.with.negation.txt)

These type of errors are coming in all the files which have been tested already

**Comment by dczulada** [comment]
This is an issue with the Cypress Validation Utility.  This should be fixed in the Thursday release.

https://jira.oncprojectracking.org/browse/CYPRESS-678
