### ISSUE TITLE
500 error when trying to view Master patient list/Add Product on VirtualBox

### ISSUE THREAD

**Issue by srmouse82** [projectcypress/cypress#565]
I'm running Cypress 3 beta1 on VirtualBox. I'm able to add a log in but I get a 500 error when trying to view the master patient list or add a new product. Attached is the log file.

[production.txt](https://github.com/projectcypress/cypress/files/348527/production.txt)

**Comment by ssayer** [comment]
We released beta2 last Thursday. Can you try a fresh install and let us know if your'e able to create products?

**Comment by ssayer** [comment]
@srmouse82 Is this issue still occurring for you in beta2?

**Comment by srmouse82** [comment]
@ssayer  I've been trying to get beta2 to work, but I can't get it to work on virtual box. Not sure what the problem is,  I will keep trying and let you know.

**Comment by rbclark** [comment]
Are you getting a specific error when importing the VM on beta2?

**Comment by srmouse82** [comment]
@rbclark  I'm getting this error: 

Failed to import appliance C:\Users\srmouse\Downloads\Cypress_CVU.v3.0.0beta2_Public_VM.ova.

Could not read the file 'cypresscvuv300beta2-disk1.vmdk.gz' (VERR_SHARING_VIOLATION).

Result Code: VBOX_E_FILE_ERROR (0x80BB0004)
Component: ApplianceWrap
Interface: IAppliance {8398f026-4add-4474-5bc3-2f9f2140b23e}

**Comment by srmouse82** [comment]
I did get it to run on VMWare though.

 @ssayer the 500 error is still happening when trying to add a product. I am still able to add a vendor, but that's about it.

**Comment by ssayer** [comment]
@srmouse82 go into the Admin tab and select "Bundles" then set a default bundle. This should fix the product creation bug. This is only a workaround, but we're working on solving this issue.

**Comment by ssayer** [comment]
We're tracking this actual fix for the production creation in #583, so I'm going to close this ticket. let me know if you have any further issues.
