### ISSUE TITLE
3.0 Beta 2 VM - error "rake aborted! SocketError: gettaddrinfo: Name or service not known

### ISSUE THREAD

**Issue by gitouttatown** [projectcypress/cypress#578]
This happened with Beta 1 as well, and I can't get past it. When I enter the command to download the bundles, I get the error shown below. 
![image](https://cloud.githubusercontent.com/assets/15641861/16710057/7603d26a-45df-11e6-9e11-ba4c9e32c929.png)

I am running this  on VMWare. I notice that it says I will have to ssh into the server, but I simply logged into the VM via the VMWare window. Is that the problem?

**Comment by rbclark** [comment]
Are you running behind any sort of corporate proxy? I have retested using VMWare Workstation 12 Player on the Beta2 VM on an unrestricted network and have so far been unable to reproduce the issue. Could you provide the output of the following commands just to verify? 

    ip link show

    ifconfig

Also have you changed any other settings with respect to the VM, such as the network interfaces or is it completely unchanged?

**Comment by gitouttatown** [comment]
I have not changed anything. I am running the VM from an external drive because my internal hard drive did not have room. That meant that I also had to specify the external drive as the storage location for the VM. I would not expect that to matter but I don't know.

Regarding the network / proxy: I am connected to our company's VPN but still have internet access w/out going through the VPN. Here is the output of the ip link show and ifconfig
![image](https://cloud.githubusercontent.com/assets/15641861/16741058/e6331868-475e-11e6-8b3a-78edda24134b.png)

**Comment by rbclark** [comment]
Okay it looks to me like your network interfaces are coming up correctly, so this is most likely an issue being caused by the corporate VPN or proxy. There are a few different things you can try, for one I would see how it works after you disconnect from your VPN if possible. Second I would see if there are any proxy settings on your network (you can double check easily by using a site such as http://amibehindaproxy.com/). If you are behind a proxy then those settings will need to be configured in order for you to be able to get out. You may have better luck configuring the machine while not behind a proxy in order to make things easier on you if the proxy does turn out to be the problem.

**Comment by gitouttatown** [comment]
Thank you. 
While the "amibehindafirewall" showed that I am not behind a firewall, I disconnected from our VPN anyway and tried again.
This time I got the downloads for measures, patients, value sets and results.. I also noted that at least once I had mistyped the password for my VSAC account so I am not sure which caused the problem.

Now that the value sets etc. have been loaded, I am looking for any additional documentation on how to connect to the VM from outside the VM e.g. from a web browser running on the same physical machine that is running the VMWare environment.  Different topic, I know - but if there is a quick pointer to such documentation I would appreciate it.

**Comment by rbclark** [comment]
Glad to hear that was the problem! As for your other question, you will need to go up to the network interface icon shown on the top right of your VM, right click and go to settings, and then change your network interface type from NAT to bridged and restart your VM.

**Comment by gitouttatown** [comment]
Now I can connect to it, and am working on registering products etc.
Thanks!
