### ISSUE TITLE
3.0 Beta 2 VM - error "rake aborted! openURI :: HTTPError: 404 Not Found

### ISSUE THREAD

**Issue by sudhir-nair** [projectcypress/cypress#579]
3.0 Beta 2 VM - error "rake aborted! openURI :: HTTPError: 404 Not Found
![capture](https://cloud.githubusercontent.com/assets/18002170/16722623/7adbfdda-4765-11e6-9eeb-fc5012200d3b.JPG)

**Comment by ssayer** [comment]
We uploaded the new 2015 bundle to the wrong location. Please try and again and let us know if you continue to have an issue.

**Comment by sudhir-nair** [comment]
Thanks..It looks to be working.
