### ISSUE TITLE
3.0 Beta VM error "You are not authorized to access this page." when trying to create a new vendor.

### ISSUE THREAD

**Issue by demophobos** [projectcypress/cypress#580]

**Comment by ssayer** [comment]
Are you using beta1? If so. please download and try using beta2

**Comment by demophobos** [comment]
Beta 2 (vm image) cannot be imported with the following error:
Failed to import appliance

C:...\Downloads\Cypress_CVU.v3.0.0beta2_Public_VM.ova.

Could not open the medium storage unit 'D:\QRDA_2016\temp_cypresscvuv300beta2-disk1.vmdk.gz'.

VD: error VERR_SHARING_VIOLATION opening image file 'D:\QRDA_2016\temp_cypresscvuv300beta2-disk1.vmdk.gz' (VERR_SHARING_VIOLATION).

Result Code: VBOX_E_FILE_ERROR (0x80BB0004)
Component: ApplianceWrap
Interface: IAppliance {8398f026-4add-4474-5bc3-2f9f2140b23e}

Beta 1 was imported without any problems.

**Virtual box version: 5.0.24**

**Comment by ssayer** [comment]
@demophobos It looks like you've already opened another ticket for the VirtualBox issue. I'll close this and we'll address the new issue in the other ticket.
