### ISSUE TITLE
Beta_2 install error:  OpenURI: 404 not found 

### ISSUE THREAD

**Issue by dantohe** [projectcypress/cypress#582]
The error has been mentioned before - I get it after issuing the following command as part as install on a VMWare player. I am using Beta2.

/opt/ruby_build/builds/opt/cypress/bin/bundle exec rake bundle:download_and_install version=2015-beta-20160707 RAILS_ENV=production

![error_beta2](https://cloud.githubusercontent.com/assets/11204633/16743837/3d13dbd2-477c-11e6-85e2-0f460cefbc50.png)

**Comment by ssayer** [comment]
This is not the same error as was entered before. That error was a 404 which was because the bundle was not in the correct location. Your error is a 401 Unauthorized error. It is likely that you entered your UMLS credentials incorrectly

**Comment by dantohe** [comment]
well - I don't think that's the reason as I doubled checked my credentials on Value Set Auth.  (https://vsac.nlm.nih.gov/). Still exploring the possibility of a proxy messing up something. A lot of us are behind corporate networks (and VPNs) that have special policies.

**Comment by ssayer** [comment]
If you follow the instructions in Step #2 of the [source code install instructions](https://github.com/projectcypress/cypress/wiki/Cypress-3.0.0-Install-Instructions), it should setup the proxy.

**Comment by dantohe** [comment]
OK - this issue can be closed as it turn out to be a proxy or VPN issue. I managed to install it and bring it up.
I get another issue though when I try to create a product under a vendor. 
I will open another issue regrading this.
Thanks for your help.
