### ISSUE TITLE
"Server Error" while trying to create a product 

### ISSUE THREAD

**Issue by dantohe** [projectcypress/cypress#583]
After a vendor was created, while trying to add a product the following error appears:
![error_2](https://cloud.githubusercontent.com/assets/11204633/16753142/432cc6c6-47b5-11e6-8f08-b958826a6051.png)

**Comment by ssayer** [comment]
Can you please post/send us the the server log? It should be located at /opt/ruby_build/builds/opt/cypress/log/production.log. If you don't want to post it publicly, you can send it to me at ssayer@mitre.org

**Comment by dantohe** [comment]
Are you sure this is the log location?

**Comment by rbclark** [comment]
The log location should be `/opt/cypress/log/production.log`.

**Comment by dantohe** [comment]
I sent the log to Samuel Sayer.
Please let me know if not received.

**Comment by ssayer** [comment]
Which bundle did you install? It look like Cypress is not able to find a bundle.

**Comment by dantohe** [comment]
2015-beta-20160707
using
/opt/ruby_build/builds/opt/cypress/bin/bundle exec rake
bundle:download_and_install version=2015-beta-20160707 RAILS_ENV=production
I don't need 2016 measures yet.
Daniel

**Comment by dantohe** [comment]
Any status or possible ETA on this one?
Thanks

**Comment by ssayer** [comment]
The issue is that Cypress is not finding a default bundle. You should be able to set a default bundle through the admin interface (which is available through the admin link in the menu bar).  Select the bundle tab and set the bundle as default. If this does not work, please let me know.

**Comment by dantohe** [comment]
I do not have the admin interface - I tried bundle exec rake ad_admin but
not luck.

**Comment by ssayer** [comment]
can you paste in which command you ran (exactly as typed) and the output?

**Comment by dantohe** [comment]
please see attached.
Thanks
Daniel

**Comment by ssayer** [comment]
I think your attachment didn't come through in your email post. I think you might have to attach it directly to a comment.

**Comment by dantohe** [comment]
emailed it to you

**Comment by sgnana** [comment]
I overcame this by modifying the default_bundle property in /opt/cypress/config/cypress.yml. I set it to the version of the bundle I had imported into MongoDB (in my case "2015.0.0"). Now, both "add product" and "Master Patient List" are working.

**Comment by ssayer** [comment]
Did you both do fresh installs? 

@sgnana can you tell me which bundle version you have installed?

We haven't been able to reproduce this issue yet where Cypress doesn't find a default bundle.

**Comment by dantohe** [comment]
what do you mean fresh install? - I mounted the image provided and just specified the bundle

**Comment by ssayer** [comment]
Yes, that is a fresh install. Sometimes users will update an older version on a VM or use an older bundle, which can cause Cypress to behave erratically. We just pulled down the Cypress VM and installed the latest 2015 (2015.0.0) bundle on it and were not able to reproduce this issue.

**Comment by dantohe** [comment]
@sgnana trick worked - changing the default_bundle to point to 2015 seems to let me create a product - still, this is a workaround

**Comment by sgnana** [comment]
Yes, I think I had to settle for a diff bundle since the 2015-beta20160707 version failed while importing into the ValidatorUtil. So I imported the 2015-beta20160623 bundle from demo.projectcypress.org/bundles.

Thanks
Gnana



Pardon typos, emailing from my phone


-------- Original message --------

**Comment by ssayer** [comment]
It seems the issue had to do with different install methods for the bundle. In testing I previously mentioned we had used the bundle upload through the UI that sets the default correctly. The rake script did not. The install instructions for RC1 now use the UI, so this should no longer be an issue
