### ISSUE TITLE
" Error: Please install a 2016 Cypress bundle in order to use the Cypress Validation Utility"

### ISSUE THREAD

**Issue by gitouttatown** [projectcypress/cypress#584]
I downloaded the bundle for 2016-beta-20160623 first.
I created a company, and a product. Set the product to certify for c1, c2 and c3.
I selected measures. I looked at how to download QRDA I files for patients and could not find any way. Decided it must be the "Validation Utility" that does that. 
Clicked on the tab for it and after a long time, got this error:
![image](https://cloud.githubusercontent.com/assets/15641861/16763616/d7c472bc-47e6-11e6-8544-6dc8812d9fe7.png)

It looks like it thinks I am trying to upload files?
Anyway I thought maybe it wanted me to download the *other* bundle first so I went back and downloaded the 2015-beta-20160707 bundle as well, and tried again with the validation tab. Same result.

What does it take to get QRDA I files for import?

**Comment by rbclark** [comment]
Are you running the commands:

    sudo su - cypress
    cd /opt/cypress
    /opt/ruby_build/builds/opt/cypress/bin/bundle exec rake bundle:download_and_install version=BUNDLE_VERSION RAILS_ENV=production

If so that might be the issue, as of right now cypress and the cypress validation utility do not share the same database in production mode. The bundles can be imported into the validation utility with the following commands

    sudo su - cypress
    cd /opt/cypress-validation-utility
    /opt/ruby_build/builds/opt/cypress-validation-utility/bin/bundle exec rake bundle:download_and_install version=BUNDLE_VERSION RAILS_ENV=production

**Comment by gitouttatown** [comment]
I got past that problem.  I was trying to create test data for a product where I had listed that the product wanted the 2017 measures, using bundle 2016-beta-20160623. It did not like that, and it was giving me a very unhelpful error message which was throwing me off. 
Then I remembered the statement in last week's tech talk that the 2017 measures will not be available until 7/28 at the earliest, or whenever CMS finalizes them, whichever is later.

So I created another product and specified 15 measures from the 2016 reporting set. This time, I was able to start it generating test data. However, it's been running for almost 5 hours and has completed 2  measures. It seems to be stuck on "CMS55v4	Median Time from ED Arrival to ED Departure for Admitted ED Patients" - which should not be very complex.

Should I kill this or is there a chance it will finish? It should be able to create test patients for a list of 15 measures but if I have to create them one by one I guess I can try that.

**Comment by ssayer** [comment]
To be clear, we have released the measures created in 2016 for the 2017 reporting year for Cypress and CVU. The measures that will be released in 2017 for the 2018 reporting year will not be supported by Cypress until next year. The feature that was delayed till the final release is the QRDA validation required by CMS for the 2017 reporting year. EH validation rules will be included in the final Cypress release, but the EP/EC side has been delayed until an unknown date in the future.

That job is likely in error, we are currently developing an update for the final release that will mark calculation as failed instead of it spinning. You shouldy kill it and try a new one.

**Comment by gitouttatown** [comment]
I was about to kill it based on your advice but when I just checked, after 5 hours, it has now completed 4 out of 15 measures so I am not killing it yet. It finally got through CMS 55 and CMS 111. At this rate it will take more than 15 hours to complete. Should I have configured the VM with more ram or something?

**Comment by ssayer** [comment]
This is not expected behavior, and we haven't encountered this happening with that default configuration. We'll look into this and see if we can reproduce it. If the files have no PII/PHI, could you post them here so we can try running them our instance?

**Comment by okeefm** [comment]
@gitouttatown: How much RAM do you have the application configured with?

**Comment by gitouttatown** [comment]
I have changed nothing on the VM image I downloaded. I am running it with VMWare Workstation Player 12 on top of Windows 7.  

I don't know how to answer your question about how much RAM the application is configured with. 

As for sending files, I am happy to do so if you can tell me what files you want. No PHI is involved at this time. 

At the moment, 6 of 15 measures have completed. The top command on the VM shows that ruby task has been running 193 minutes over the past 5+ hours, if that helps.

![image](https://cloud.githubusercontent.com/assets/15641861/16773999/50497478-4817-11e6-9581-6f6b87532e32.png)

**Comment by ssayer** [comment]
My mistake, I thought the jobs were running in the CVU, not Cypress. I had wanted to evaluate the submitted files, but it sounds like you didn't submit anything yet. Has there been any progress on the other jobs?

**Comment by gitouttatown** [comment]
Yes it is racing along. 13 out of 15 measures complete (generating data files) after 10+ hours.
![image](https://cloud.githubusercontent.com/assets/15641861/16783363/ea0f980c-4840-11e6-814f-37fc8453ff54.png)

**Comment by ssayer** [comment]
Can you tell us which 15 measures you've selected? We'll see if we can reproduce this issue.

**Comment by gitouttatown** [comment]
Yes. The measures I selected are the ones listed in the IPPS proposed rule for 2017 reporting to the hospital IQR program. (but the versions below are for 2016 reporting)
55v4
111v4
104v4
71v5
72v4
105v4
107v4
102v4
108v4
190v4
9v4
113v4
53v4
31v4
26v3

Update: after 23 hours, I hit F5 to refresh the browser (Chrome). It had been updating the display earlier but had stuck at 13 / 15. When I refreshed the display it showed that Cypress had logged me out. When I logged back in, it showed that it had completed files for all 15 measures so I downloaded them.  

I then tried again to create the same 15 measures with the 2017 reporting year logic/value sets but it failed. It would only do 13/15 so I created the other two manually after removing them from the main product definition.  I had to break out CMS 26 and CMS 53 into separate test files by creating one "product" to test each of those.

Regarding the slowness: I was running the VM on an external 1TB USB hd with a USB 2 interface. I have since managed to clear enough space to run it on my internal HD and it may be running faster. However it is hard to tell because it seems that it may be using referencing test files already created now when I ask it to generate tests for various measures.

**Comment by ssayer** [comment]
The external drive could explain the slowness. It's not an environment we've really tested, so it's hard to know for sure (I haven't heard of anyone trying this before). I'll see if we can reproduce the failures with CMS26 and CMS53.

**Comment by gitouttatown** [comment]
Thanks. To clarify: Creating a product with *just* CMS26 and other with *just* CMS 53 was successful in generating files for download almost instantly.

**Comment by ssayer** [comment]
We have tested this case on several different deployments of Cypress and are unable to replicate the two measures failing when grouped with the others.
