### ISSUE TITLE
Beta 2 (vm image)  cannot be imported with the following error:

### ISSUE THREAD

**Issue by demophobos** [projectcypress/cypress#585]
Failed to import appliance 

C:\...\Downloads\Cypress_CVU.v3.0.0beta2_Public_VM.ova.

Could not open the medium storage unit 'D:\QRDA_2016\temp_cypresscvuv300beta2-disk1.vmdk.gz'.

VD: error VERR_SHARING_VIOLATION opening image file 'D:\QRDA_2016\temp_cypresscvuv300beta2-disk1.vmdk.gz' (VERR_SHARING_VIOLATION).

Result Code: VBOX_E_FILE_ERROR (0x80BB0004)
Component: ApplianceWrap
Interface: IAppliance {8398f026-4add-4474-5bc3-2f9f2140b23e}

Beta 1 was imported without any problems.

**Virtual box version: 5.0.24**

**Comment by rbclark** [comment]
I am able to reproduce this using Virtualbox 5.0.24 and it seems to be a bug with that specific version on Windows. Would you be able to upgrade to the latest virtualbox (5.1.0) and see if the issue persists? So far I have only been able to reproduce it on 5.0 and not 5.1.

**Comment by demophobos** [comment]
Thanks a lot, Clark! It does work.
