### ISSUE TITLE
Taking latest visit if admited again within 24 hours of discharge for Measure Calc

### ISSUE THREAD

**Issue by souravkhemka** [projectcypress/cypress#586]
Hi, 

For CMS55, a patient named"3 N SCIP" has encounter 1 as 
<low value='20140508060000'/>
      <high value='20140512050000'/>
and another encounter 2 as
 <low value='20140512060000'/>
      <high value='20140520100000'/>

So, the second encounter is only considered for measure calculation wherein Cypress says all visits should fall under measure calculation (atleast IPP)
PFA the patients file
[31_3_N SCIP.txt](https://github.com/projectcypress/cypress/files/361801/31_3_N.SCIP.txt)

**Comment by souravkhemka** [comment]
Encounter 1 has
startdate=20140508060000
enddate=20140512050000
Encounter 2 has
startdate= 20140512060000
enddate=20140520100000

**Comment by dczulada** [comment]
Hi-

You may be having an issue with how you are evaluating specific occurrences.  This statement is from section 2.8.5 of the Quality Data Model version 4.2, "Conditions applied to specific occurrences carry forward from one population to the next, in the order in which they are calculated. See the eCQM Logic and Implementation Guidance5 for details on the calculation order of the measures."

The Patient "3 N SCIP" has three encounters with code 32485007 from the Encounter Inpatient valueset (2.16.840.1.113883.3.666.5.307).  All three of these encounters satisfy the ("length of stay <= 120 day(s)" and "ends during Measurement Period") conditions.

Encounter 1 - January  29-31
Encounter 2 - May 8-12
Encounter 3 - May 12-20

As a result, this patient has a count of 3 visits for the IPP.

None of the encounters are within an hour of an Emergency Department visit, and therefore are not in the Measure Population.

-Dave Czulada
