### ISSUE TITLE
Error while parsing files on Validator

### ISSUE THREAD

**Issue by souravkhemka** [projectcypress/cypress#589]
PFA the QRDA I file
[Enc Active1.txt](https://github.com/projectcypress/cypress/files/363780/Enc.Active1.txt)

and the error image
![error](https://cloud.githubusercontent.com/assets/20084778/16840588/189da688-49f3-11e6-8e38-889c7adf831b.png)

**Comment by dczulada** [comment]
Thanks for pointing this out.

The Validator should have returned an error message regarding an error in the XML below.  The priorityCode should be using a code from an "Attribute" valueset.

-Dave Czulada

<priorityCode code="48794007" codeSystem="2.16.840.1.113883.6.96" codeSystemName="SNOMEDCT" displayName="Human immunodeficiency virus infection with infectious mononucleosis-like syndrome (disorder)" sdtc:valueSet="2.16.840.1.113883.3.464.1003.120.12.1003" />

**Comment by dczulada** [comment]
`<priorityCode code="48794007" codeSystem="2.16.840.1.113883.6.96" codeSystemName="SNOMEDCT" displayName="Human immunodeficiency virus infection with infectious mononucleosis-like syndrome (disorder)" sdtc:valueSet="2.16.840.1.113883.3.464.1003.120.12.1003" />`
