### ISSUE TITLE
Issue with cypress validator

### ISSUE THREAD

**Issue by AllMedsmurdock** [projectcypress/cypress#601]
Element '{urn:hl7-org:v3}id', attribute 'root': '604F3C60-99FC-4C4BB224-6A22D74E84E7' is not a valid value of the union type '{urn:hl7-org:v3}uid'. 

I am getting the above validation error. The node looks like and the root UDID is correct for 2016.
So what is the issue?

[nodeUDID.txt](https://github.com/projectcypress/cypress/files/369966/nodeUDID.txt)

**Comment by dczulada** [comment]
What Measure is this UUID from?  It looks like the one above is missing the third dash (4C4B-B224).

Here is an example of a valid UUID for the NUMER for CMS CMS53v4.  886D9EDE-A988-4FE9-9514-9099CEFAA804.

**Comment by AllMedsmurdock** [comment]
Thanks that was it,
