### ISSUE TITLE
unit checking wrong in cms 77 testing

### ISSUE THREAD

**Issue by saionc** [projectcypress/cypress#606]
We found this while testing with Cypress 3.0 alpha 6 and found this to be present in Cypress 3.0 Beta 2 as well. The patient ‘HIV_Peds B’ has the lab result for ‘HIV Viral Load’(2.16.840.1.113883.3.464.1003.120.12.1002) expressed in the unit ‘cells/ml’. We believe that the unit should be ‘copies/mL’ which is the standard unit for that test and this is the unit that is mentioned in the HQMF. Can you confirm that this will be updated in the final version of Cypress 3.0 ?

**Comment by dczulada** [comment]
Yes, this will be in the final version of the bundles.  This was actually updated in the beta bundles released on June 23rd.
