### ISSUE TITLE
Unit percent in string type

### ISSUE THREAD

**Issue by MatthewDynamic** [projectcypress/cypress#611]
Cypress patients N Heart 1 and N Heart 2 have
`<value xsi:type="ST" >12%</value>`
in entry for "Risk Category Assessment: Framingham coronary heart disease 10 year risk"
These are the only two patients I could find like this but there may exist others.

I believe this should be coded as:
`<value xsi:type="PQ" value="12" unit="%"/>`

**Comment by ssayer** [comment]
Thanks for letting us know. We've found about 10 patients that have this issue. We'll have this updated for the final bundle

**Comment by ssayer** [comment]
This should be addressed in the latest 2015-RC1 and 2016-RC2 bundles
