### ISSUE TITLE
Unit mismatch "weeks"

### ISSUE THREAD

**Issue by MatthewDynamic** [projectcypress/cypress#618]
At least the following patients use the unit "weeks" while measures use the unit "wk".

1 N Newborn
2 N Newborn
4 N Newborn
1 N OB
2 N OB
NEWBORN A
NEWBORN B
OB A
OB B

**Comment by ssayer** [comment]
Thanks for this Matt. We may not get this into the RC1 bundles, but we'll have it updated for the final bundle

**Comment by ssayer** [comment]
This is fixed int he latest 2015-rc1 and 2016-rc2 bundles
