### ISSUE TITLE
Please install a 2016 Cypress bundle

### ISSUE THREAD

**Issue by garrett-allscripts** [projectcypress/cypress#619]
After mounting the Cypress 3.0Beta 2 image,
- I downloaded the bundle version 2015-beta-20160707 which went fine.  
- I did run into a hiccup installing the validator.  Version  2015-beta-20160707 could not be found, so after searching this forum, I found Version 2015-beta-20160623.  The download went fine
`/opt/ruby_build/builds/opt/cypress-validation-utility/bin/bundle exec rake bundle:download_and_install version=2015-beta-20160623 RAILS_ENV=production`

2 questions:
Will the slight version differences cause a problem?  The xml validator seems to be working:
![xmlvalidation](https://cloud.githubusercontent.com/assets/20567594/17006894/307e737c-4eb2-11e6-9026-bd8f2e5e6427.jpg)

But when I go to the Validation Tab, I get:  "Error: Please install a 2016 Cypress bundle in order to use the Cypress Validation Utility"  Any ideas on how to debug this?

Thank you,
Garrett

**Comment by ssayer** [comment]
The XML validation in the two bundles is the same, some of the patient definitions are different. This should only affect the certification tool and not the CVU.

If you restart the server, the "please install measure bundle" message should go away.

**Comment by garrett-allscripts** [comment]
Thank you.
