### ISSUE TITLE
CMS 55 and 111 "Could not find value for Population MSRPOPLEX"

### ISSUE THREAD

**Issue by MatthewDynamic** [projectcypress/cypress#626]
CMS55 v4 and CMS111 v4 (2015 release) are again reporting "Could not find value for Population MSRPOPLEX" though the measures do not have Measure Population Exclusions. 

I am seeing this error via the API. I suspect 179 has the same error but I have not tested it recently.

**Comment by dczulada** [comment]
Matt-

Thanks.  These IDs were not removed from 

CMS55, CMS111 and CMS179 for the 2015 release and CMS179 for the 2016 release.  They will be removed in the final bundle.

-Dave
