### ISSUE TITLE
500 Error when viewing "C2 and C3" results page

### ISSUE THREAD

**Issue by MatthewDynamic** [projectcypress/cypress#627]
I am getting a 500 error when trying to view the results of the C2 C3 test. I can send the QRDA3 via email if that would help. I have attached the portion of the log generated when viewing that page. 

[500 error log portion.txt](https://github.com/projectcypress/cypress/files/380316/500.error.log.portion.txt)

**Comment by ssayer** [comment]
There error in the log is "Zip end of central directory signature not found"

I think you might have uploaded the QRDA3 on the C1 test page because it looks like it's expecting a zip file.

**Comment by ssayer** [comment]
Alternatively, try switching your content type to "text/xml". It looks like RC1 and earlier releases only look for text/xml instead of the multitude of other xml types. This has already been fixed in master and will be fixed for the final release.

**Comment by MatthewDynamic** [comment]
Ok. That helps me get to the bottom of it. I am using the .Net SDK and it appears the tasks for C1 and C2 are not returned in the same order every time.

**Comment by ssayer** [comment]
You can lookout at the task "type" attribute to determine if it's a C1 or C2 task.
