### ISSUE TITLE
Discontinue use of GitHub Issues for Cypress 3.0

### ISSUE THREAD

**Issue by ssayer** [projectcypress/cypress#669]
Please file issues to https://oncprojectracking.healthit.gov/support/browse/CYPRESS

**Comment by deekim** [comment]
would it make sense to disable the creation of issues?
https://help.github.com/articles/disabling-issues/

and possibly just make this a note in the `README.md`

**Comment by ssayer** [comment]
We keep this open to track issues with pre-release verisons of Cypress (when those are available). The JIRA is to track issues with the production version (we keep these issues separate for various reasons). I think the information in this ticket is unclear though, so we'll make a new ticket and update the README.

Thanks for your suggestion.

**Comment by deekim** [comment]
ah gotcha. thanks for the info.
