### ISSUE TITLE
Version 2.6.1. NQF 0419 bug

### ISSUE THREAD

**Issue by demophobos** [projectcypress/cypress#671]
It seems to be a bug in NQF 0419 exspectations (reproduced by me at least twice):
**Expected Reports**: 13 patients are exspected, although only 11 have been generated. The number of patients can differ from time to time, but it always contradicts exspectations.

**Comment by ssayer** [comment]
NQF0419 is not about the number of patients, but the number of visits. Some patients may have more than one encounter which would cause the number to be greater than the number of patients
