### ISSUE TITLE
Upgrade From 2.6 to 3.0

### ISSUE THREAD

**Issue by ITuser07** [projectcypress/cypress#672]
What is the best way to upgrade from 2.6 to 3.0?

Can I utilize this process -- https://github.com/projectcypress/cypress/wiki/Cypress-3.0.0-Alpha-Upgrade-Instructions ?

Thanks,
Ryan

**Comment by ssayer** [comment]
No, 3.0 contains many breaking changes and any upgrade would likely be very unstable. Please follow the install instructions: https://github.com/projectcypress/cypress/wiki/Cypress-3.0.0-Install-Instructions

Now that the Cypress Alpha/Beta release is over, the upgrade instructions are no longer applicable. I've deleted it to prevent further confusion.

**Comment by ITuser07** [comment]
Do I have to have a freshly installed Ubuntu Server to follow the 3.0 install instructions or can I follow them on a server already running Cypress 2.6?

**Comment by ssayer** [comment]
We tested in the install instructions on a fresh server. We have not attempted to update a 2.6 server 3.0 as many of the dependencies require different versions between 2.6 and 3.0
