### ISSUE TITLE
Creating A User v3.0

### ISSUE THREAD

**Issue by ITuser07** [projectcypress/cypress#674]
Good Afternoon,
   I've followed the v3.0 installation instructions and got it successfully installed and am able to access the web portal.  The last step doesn't appear to be an open for me though, it states Click on the "Create New User" link to add a new user and to get started with Cypress.  I do not have a Create New User link, all I have is a signup link which requests an email and password.  I attempted to signup but then didn't have the admin button that it's referencing in in the Cypress Initial Setup for the Bundle Install and I'm not able to follow the steps at the bottom to add the admin button because the cd /opt/cypress directory doesn't exist.  

Insight on this would be appreciated. :)

**Comment by ITuser07** [comment]
Good Morning,
   The dept that will be utilizing this for the Meaningful Use Testing would like to have this up and running by the 8th.  Would you happen to have any update on my issue above?

Thanks,
Ryan

**Comment by dczulada** [comment]
How did you install Cypress?  Did you follow the Custom Install?

Try: cd /home/cypress/cypress

**Comment by ITuser07** [comment]
yep, I followed the custom install and I do have a /home/cypress/cypress directory.

**Comment by dczulada** [comment]
It looks like those instructions need to get updated to reference the final release.

In that directory, you will want to run the following command

git checkout v3.0.0 -b 3.0.0

and then

bundle exec rake cypress:add_admin[EMAIL] RAILS_ENV=production

Let me know if that works for you

**Comment by ITuser07** [comment]
Thank you so much for responding.  Now sure that worked though.

Here is the output:

**cypress@MU2CERT2:~/cypress$** git checkout v3.0.0 -b 3.0.0
**fatal: A branch named '3.0.0' already exists.**
**cypress@MU2CERT2:~/cypress$** bundle exec rake cypress:add_admin[Ryan.Bell@mcis.com] RAILS_ENV=production
/home/cypress/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/http/mime_type.rb:163: warning: already initialized constant Mime::ZIP
/home/cypress/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/http/mime_type.rb:163: warning: previous definition of ZIP was here
/home/cypress/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/http/mime_type.rb:163: warning: already initialized constant Mime::XML
/home/cypress/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/actionpack-4.2.5.2/lib/action_dispatch/http/mime_type.rb:163: warning: previous definition of XML was here
rake aborted!
Devise.secret_key was not set. Please add the following to your Devise initializer:

  config.secret_key = 'bbce07416090b8d5e598a9b0650eea729632ea45c1d274cbaae5dfd599be667c035cc5da76e138eac56912a4066bee76c19ff6431f059efa50da45b758bf715c'

Please ensure you restarted your application after installing Devise or setting the key.
/home/cypress/cypress/config/routes.rb:2:in `block in <top (required)>'
/home/cypress/cypress/config/routes.rb:1:in `<top (required)>'
/home/cypress/cypress/config/environment.rb:5:in `<top (required)>'
/home/cypress/.rbenv/versions/2.2.5/bin/bundle:23:in `load'
/home/cypress/.rbenv/versions/2.2.5/bin/bundle:23:in `<main>'
Tasks: TOP => cypress:add_admin => cypress:setup => environment
(See full trace by running task with --trace)

**Comment by ITuser07** [comment]
Because it said the secret key was not set I also tried running the command as 
bundle exec rake cypress:add_admin[MY EMAIL] RAILS_ENV=production SECRET_KEY_BASE=$secret_key

**Comment by ITuser07** [comment]
Ok I added config.secret_key = '-- secret key --' to the devise.rb file and now I'm getting further.  

Now its just telling my my email address isn't found even though I signed up and used the same character case.

**Comment by ITuser07** [comment]
Got it, when I signed up I capitalized the first letter of my first and last name, but in the system it was actually all lower case.

**Comment by ITuser07** [comment]
Guess this can be closed now then.  Got my account setup with the admin button and got the 2015 and 2016 bundles imported.

The only other problem i'm seeing is that when I click the Validation utility button it says that 
Page Not Found

We're sorry but Cypress can't find this page. You might have followed a bad link or mis-typed a URL.

Should I open this as a new issue?

**Comment by okeefm** [comment]
The Validation Utility link on a local install of Cypress points at a local copy of the Cypress Validation Utility, which needs to be installed separately from the Cypress application. If you have not installed the Cypress Validation Utility and configured the web server to serve it, that link will generate the error message you are seeing.

**Comment by rbclark** [comment]
The [initial setup instructions](https://github.com/projectcypress/cypress/wiki/Cypress-3.0-Initial-Setup) have been updated to include a caveat about the custom install instructions which was identified here.

**Comment by dczulada** [comment]
Ryan

The "git checkout v3.0.0 -b 3.0.0" command would have been if you were starting from scratch.

since you already have a 3.0.0 branch, run the command below.  It should pull in all updates.

"git rebase v3.0.0"

**Comment by ITuser07** [comment]
Thank you OkeeFM and dczulada.  Could you please tell me is the validation Utility new in 3.0?  Is that something thats needed and would you recommend that I install it?

**Comment by ssayer** [comment]
The CVU is not required for certification. It is a utility for testing arbitrary QRDA files.

**Comment by ITuser07** [comment]
We will be generating QRDA files so if that something we can use to validate the format prior to submission, then yes I think we want it.  How do I go about getting that.  Is there an installation document?

**Comment by ITuser07** [comment]
Or can that button just be pointed to https://validator.projectcypress.org/ ?

**Comment by ITuser07** [comment]
Anymore information on this?

Thanks for your time!

**Comment by dczulada** [comment]
Here are installation instructions for the CVU

https://github.com/projectcypress/cypress/wiki/Cypress-Validation-Utility-Custom-Install-Instructions

**Comment by ITuser07** [comment]
Ok, so those instructions add the CVU as the home page?  How do I just link the CVU page to the CVU button in the navigation bar?

**Comment by rbclark** [comment]
Those instructions will install the Cypress Validation Utility on the server, if you wish to install them side by side then the steps will be extremely similar however you will need to set the port to 8080 instead of 80 for the CVU and add a redirect from /cvu to port 8080. I strongly suggest using the provided Chef recipes for this as they handle all of this for you. https://github.com/projectcypress/cypress-recipe#installation-options

**Comment by ITuser07** [comment]
Great thank you.  Will running the chef recipe have any negative impact on the current custom install?

**Comment by rbclark** [comment]
Unfortunately it does install cypress in a slightly different manner, meaning that it does not play too nicely. If you want to keep your current install how it is then go ahead and follow the CVU custom install instructions, only update your NGINX config to look similar to the following

    upstream primary {
      server localhost:8000;
    }

    upstream secondary {
      server localhost:8001;
    }

    server {
      listen 80;
      server_name _;

      root /home/cypress/cypress/public; 

      try_files $uri/index.html $uri @app;

      location @app {
        proxy_pass http://primary;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
      }

      location /cvu {
        return 301 http://$host:8080;
      }

      error_page 500 502 503 504 /500.html;
      client_max_body_size 4G;
      keepalive_timeout 10;
    }

    server {
      listen 8080;
      server_name _;

      root /home/cypress/cypress-validation-utility/public;

      try_files $uri/index.html $uri @app;

      location @app {
        proxy_pass http://secondary;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
      }

      error_page 500 502 503 504 /500.html;
      client_max_body_size 4G;
      keepalive_timeout 10;
    }

**Comment by ITuser07** [comment]
That worked fantastic!  Thanks a lot, I really appreciate your time and patience!  I'm satisfied :)
