### ISSUE TITLE
Undefined Namespace in Manual test

### ISSUE THREAD

**Issue by jwei2** [projectcypress/cypress#677]
Hi,

I am trying to view errors on a manual entry test and I am running into this error:

"Undefined namespace prefix: /*/*[19]/*/*[3]/*/*[7]/*/sdtc:dischargeDispositionCode"

The measures I am testing against are CMS 108,171,172, and 188. None of these measures even use Discharge Disposition. This is stopping me from seeing the errors causing me to fail this test. 

Thanks,

Jeff

![image](https://cloud.githubusercontent.com/assets/20824015/17380328/46cae540-598c-11e6-802e-f00a7cfdb6dd.png)

**Comment by dczulada** [comment]
Jeff, can you open a JIRA ticket (https://oncprojectracking.healthit.gov/support/browse/CYPRESS) and upload the files that are causing the errors.

-Dave Czulada
