### ISSUE TITLE
Master List Patient

### ISSUE THREAD

**Issue by satyakirankumar** [projectcypress/cypress#686]
When search the Measure from patient list. Please provide the column headers for IPP, DENOM, NUMER, DENEX, DENEXCEP for better understanding.

**Comment by dczulada** [comment]
![screen shot 2016-08-11 at 9 17 56 am](https://cloud.githubusercontent.com/assets/8173551/17589767/87dc9aec-5fa4-11e6-83f0-0d4da8a08a17.png)

The column headers are displayed on the patient list.

**Comment by satyakirankumar** [comment]
My Intention is the above. But in my login the page is not displaying the headers only for IPP, DENOM, 
![master list1](https://cloud.githubusercontent.com/assets/20966356/17614973/634f89e8-6088-11e6-8393-af0937f36637.jpg)
DENEX, NUMER.  Is there any issue with browsers? Please find the attached for your reference.

**Comment by dczulada** [comment]
Thats really odd.  How did you install Cypress?  Did you install from scratch or update an existing Alpha or Beta release?

**Comment by satyakirankumar** [comment]
No I'm using the Demo Server.​






*-------Satya Kiran Kumar Allamraju*




*--------------------------------------------------------------Privacy
Notice:The contents of this electronic message, including any prior
messages, files, or attachments transmitted with it, are CONFIDENTIAL and
are intended solely for the use of the individual(s) to whom the message is
addressed. This message may contain legally protected or privileged
information. Do not read, copy, disclose or forward this message without
authorization from the originator of this message. If you have received
this message in error, please notify the sender immediately and delete all
copies from your
system.-------------------------------------------------------------- *

**Comment by dczulada** [comment]
Thanks.  This is a bug in Cypress.

Until this is fixed, to view the 'master patient' you can navigate back to unfiltered list and select that patient you would like to view.

This bug will happen when you click on patient using the measure filter for the bundle that isn't "default"

**Comment by ssayer** [comment]
This has been addressed in Cypress 3.0.1
