### ISSUE TITLE
Patient list in cypress v3.0 demo server is not matched with the specification 

### ISSUE THREAD

**Issue by synamed** [projectcypress/cypress#693]
I see many reports have same issue. On Master Patient list i selected 2015 bundle then selected patient 1 N GP Adult who shows up in CMS22 report. However i do not see this patient's information meets its specification. I attached the spec and the information that cypress generates for CMS22. Please take a look at them and provide the correct patient list for each report to meet the specification. Thanks
![cms22](https://cloud.githubusercontent.com/assets/21073254/17724806/79205776-646f-11e6-8612-720c3bc1f8a3.png)

[EP_CMS22v4_NQFXXXX_BP_Screening_and_Follow_Up.zip](https://github.com/projectcypress/cypress/files/421777/EP_CMS22v4_NQFXXXX_BP_Screening_and_Follow_Up.zip)

**Comment by ssayer** [comment]
I believe this was addressed in the Cypress 3.0.1 patch. Please use JIRA from now on.
