### ISSUE TITLE
Incorrect command for downloading and installing the bundle in the wiki documentation

### ISSUE THREAD

**Issue by tcprescott** [projectcypress/cypress#695]
The commands listed on wiki article [Cypress Validation Utility Initial Setup](https://github.com/projectcypress/cypress/wiki/Cypress-Validation-Utility-Initial-Setup) give these commands to run to download and install the bundle for the CVU:

```
cd /opt/cypress-validation-utility
/opt/ruby_build/builds/opt/cypress-validation-utility/bin/bundle exec bundle:download_and_install version=BUNDLE_VERSION RAILS_ENV=production
```

This doesn't work.  It apparently needs to be "exec rake" like this:

```
cd /opt/cypress-validation-utility
/opt/ruby_build/builds/opt/cypress-validation-utility/bin/bundle exec rake bundle:download_and_install version=BUNDLE_VERSION RAILS_ENV=production
```

It's a relatively small thing, but it tripped me up for a while.

Thanks!
-Thomas

**Comment by okeefm** [comment]
Hello Thomas,

Good catch! I've changed the documentation to include the `rake` command.

Thanks!
Michael O'Keefe
