### ISSUE TITLE
Getting a 500 Error after logging in to cypress

### ISSUE THREAD

**Issue by cbrownabsg** [projectcypress/cypress#705]
My username is cbrownabsg.  I had entered the NLM VSAC login credentials and got to the Vendor page.  I tried to add a vendor and then got the 500 error.  After that, I now get the 500 error immediately after I log in.  
Some additional info: This issue occurred after logging in to the https://cypressdemo.healthit.gov site. The error is presented on this page: https://cypressdemo.healthit.gov/vendors.

![500 error - cypress vendor page mozilla firefox_2016-09-01_10-11-59](https://cloud.githubusercontent.com/assets/21684462/18181775/81882ce2-7052-11e6-9388-2da2a7559542.png)

**Comment by cbrownabsg** [comment]
Some additional info:  This issue occurred after logging in to the https://cypressdemo.healthit.gov site.  The error is presented on this page:  https://cypressdemo.healthit.gov/vendors

**Comment by cbrownabsg** [comment]
![500 error - cypress vendor page mozilla firefox_2016-09-01_10-11-59](https://cloud.githubusercontent.com/assets/21684462/18172817/a6c9466a-702c-11e6-9cc8-8b0b700e7a1c.png)

**Comment by ssayer** [comment]
Is this still occurring?

**Comment by cbrownabsg** [comment]
No.  It has been resolved.

Thank you for checking.
