### ISSUE TITLE
Unable to download or Upgrade Cypress 3.0.1

### ISSUE THREAD

**Issue by sudhir-nair** [projectcypress/cypress#715]
Unable to download VM or Upgrade to latest version.

While trying to Upgrade it gives error.

Command not found at line 1: 404 bash
![capture](https://cloud.githubusercontent.com/assets/18002170/18589060/957f44ec-7c46-11e6-8847-95dbd6d8db20.JPG)

**Comment by rbclark** [comment]
The VM download links have been fixed. As for the upgrade script I could you tell me what happens if you run `curl https://raw.githubusercontent.com/projectcypress/cypress/v3.0.1/contrib/upgrade_cypress_300_to_301.sh` and see the upgrade script outputted?

**Comment by ssayer** [comment]
Going to close this since there is a ticket on JIRA
