### ISSUE TITLE
Unable to Upgrade Cypress 3.0.1

### ISSUE THREAD

**Issue by sudhir-nair** [projectcypress/cypress#716]
![capture](https://cloud.githubusercontent.com/assets/18002170/18606384/23eecec0-7ccc-11e6-9789-4dcd59d46da0.PNG)

**Comment by ssayer** [comment]
Sudhir, we are awaiting your response on the JIRA ticket for this issue: https://oncprojectracking.healthit.gov/support/browse/CYPRESS-779
