### ISSUE TITLE
Cypress v3.0 Demo Server Patient List Download Error

### ISSUE THREAD

**Issue by pjiangtjc** [projectcypress/cypress#810]
I received "504 Gate way timeout" error when I tried to download master patient list.

**Comment by okeefm** [comment]
Hello @pjiangtjc; 

Can you confirm that the version of the Cypress software you are using is 3.0? If so, are you able to upgrade to 3.1.0 using the [3.1 upgrade instructions](https://github.com/projectcypress/cypress/wiki/Cypress-3.x-Upgrade-Instructions)?

Please note that the previous Cypress release (Cypress v3.0.3) enforces conformance to the HL7 QRDA Category III R1.1 for submissions using the 2016 Bundle for the 2017 Reporting Period.  The HL7 QRDA Category III R2 Implementation Guide is not backward compatible with HL7 QRDA Category III R1.1 Implementation Guide.  As a result, QRDA Category III submissions (using the 2016 Bundle) that pass in Cypress v3.0.3 will no longer pass in Cypress v3.1.0.  Additionally, these QRDA Category III submissions (that pass in Cypress 3.0.3) will not be valid for Eligible Clinician Reporting in 2017.  QRDA Category I submissions using the 2015 and 2016 bundles will not be impacted by this change.

**Comment by wahmedswl** [comment]
Hi,
   I have docker based cypress v3.1.0 and when exporting MPL, i got 

![image](https://cloud.githubusercontent.com/assets/15020561/24909879/3b239fe8-1edf-11e7-9bea-9d0fec8ecb61.png)

any help would be appreciated.

Thanks

**Comment by dczulada** [comment]
This is addressed in Cypress 3.2
