### ISSUE TITLE
Permission denied @ dir_s_mkdir

### ISSUE THREAD

**Issue by mathanagopalb** [projectcypress/cypress#905]
When i create a new vendor and product in Cypress 3.2.0 version getting the below error.

Cypress encountered an internal error while building this measure. Please contact the Cypress team at https://github.com/projectcypress/cypress/issues, and include the text below:

Permission denied @ dir_s_mkdir - /home/app/cypress/public/data/upload

![image](https://user-images.githubusercontent.com/30858131/29109775-e3d1c610-7ca9-11e7-8ee0-4bb7bf6376d9.png)

**Comment by okeefm** [comment]
Hello,

Thank you for contacting us about this issue. We had some server maintenance performed a few days ago, during which the permissions of a directory were changed such that Cypress couldn't write to it. We've fixed the permissions, and Cypress seems to be working again. I'd recreate your product and it should build successfully. Please feel free to reach out if you see any additional issues.

Thank you,
Michael O'Keefe
Software Engineer, Cypress team

**Comment by karthikishorejs** [comment]
I ran into the same issue with 7.4.2 and the below command helped to run the get the tests building. 
`docker compose exec -T -u root cypress sh -lc 'mkdir -p /app/public/data/upload && chown -R app:app /app/public/data && chmod -R u+rwX,g+rwX /app/public/data'`
