### ISSUE TITLE
Internal error while building measure CMS22v6 invalid date

### ISSUE THREAD

**Issue by paulwhitten** [projectcypress/cypress#966]
For measure CMS22v6 when setting up a product in Cypress 3.2.3 receive the error.

Cypress encountered an internal error while building this measure. Please contact the Cypress team at https://github.com/projectcypress/cypress/issues, and include the text below:
invalid date

**Comment by okeefm** [comment]
Hey Paul,

Thanks for getting in contact with us! Can you create a ticket at https://oncprojectracking.healthit.gov/support/projects/CYPRESS/ ? This is the public issue tracker for Cypress, and will enable us to help you more efficiently. When you post there, include the version of Cypress you're using (3.2.3), the settings you were trying to use to create the product (a screenshot of the product creation page would work well), and what instance of Cypress you're using (the demo server at https://cypressdemo.healthit.gov, an internally hosted instance, etc.).
